services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-db
    restart: always
    environment:
      - 'MYSQL_DATABASE=job_search_db'
      - 'MYSQL_PASSWORD=passw0rd'
      - 'MYSQL_ROOT_PASSWORD=passw0rd'
      - 'MYSQL_USER=job_search_user'
    ports:
      - '3306:3306'
