services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=job_search_db'
      - 'MYSQL_PASSWORD=passw0rd'
      - 'MYSQL_ROOT_PASSWORD=passw0rd'
      - 'MYSQL_USER=job_search_user'
    ports:
      - '3306:3306'
    volumes:
      - ./db_schema:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
volumes:
  db_data: {}